name: Sync and Build 

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      with:
          source-repo: "git@github.com:iptvjs/iptv.git"
          destination-repo: "git@gitee.com:iptv-cn/iptv.git"

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          gitee-username: vodtv
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: iptv-cn/iptv